from typing import List, Dict, Any

DEFAULT_OFS_DATA: List[Dict[str, Any]] = [
  {
    "id": "ofs-1",
    "companyName": "Rail Vikas Nigam Limited (RVNL)",
    "symbol": "RVNL",
    "slug": "rvnl-ofs-2026",
    "exchange": "NSE & BSE",
    "sellerName": "Government of India (President of India)",
    "sector": "Railways & Infrastructure",
    "floorPrice": 420.0,
    "currentMarketPrice": 456.8,
    "discountPercent": 8.06,
    "retailDiscountPercent": 5.0,
    "issueSizeCr": 2150.0,
    "sharesOffered": 70890000,
    "greenShoeShares": 14178000,
    "promoterPreHoldingPercent": 72.84,
    "promoterPostHoldingPercent": 67.84,
    "retailQuotaPercent": 10,
    "nonRetailDate": "2026-08-30",
    "retailDate": "2026-08-31",
    "nonRetailSubscriptionTimes": 3.42,
    "settlementDate": "2026-09-02",
    "indicativeClearingPrice": 426.5,
    "status": "Live (Retail Day)",
    "overview": "Govt of India is divesting up to 5.36% stake in RVNL to meet SEBI Minimum Public Shareholding (MPS) norms."
  },
  {
    "id": "ofs-2",
    "companyName": "Mankind Pharma Limited",
    "symbol": "MANKIND",
    "slug": "mankind-pharma-ofs",
    "exchange": "NSE & BSE",
    "sellerName": "Promoter Group (Beige Ltd & ChrysCapital)",
    "sector": "Pharmaceuticals & Healthcare",
    "floorPrice": 2120.0,
    "currentMarketPrice": 2280.0,
    "discountPercent": 7.02,
    "retailDiscountPercent": 0,
    "issueSizeCr": 2450.0,
    "sharesOffered": 11556000,
    "promoterPreHoldingPercent": 76.50,
    "promoterPostHoldingPercent": 74.00,
    "retailQuotaPercent": 10,
    "nonRetailDate": "2026-08-31",
    "retailDate": "2026-09-01",
    "nonRetailSubscriptionTimes": 2.85,
    "settlementDate": "2026-09-03",
    "status": "Live (Non-Retail)",
    "overview": "Promoters and early private equity investors are offloading a 2.5% stake via OFS window to increase free-float liquidity."
  },
  {
    "id": "ofs-3",
    "companyName": "Coal India Limited",
    "symbol": "COALINDIA",
    "slug": "coal-india-ofs",
    "exchange": "NSE & BSE",
    "sellerName": "Government of India (Ministry of Coal)",
    "sector": "Mining & Energy",
    "floorPrice": 485.0,
    "currentMarketPrice": 520.4,
    "discountPercent": 6.80,
    "retailDiscountPercent": 5.0,
    "issueSizeCr": 4180.0,
    "sharesOffered": 92440000,
    "greenShoeShares": 18488000,
    "promoterPreHoldingPercent": 66.13,
    "promoterPostHoldingPercent": 63.13,
    "retailQuotaPercent": 10,
    "nonRetailDate": "2026-09-08",
    "retailDate": "2026-09-09",
    "settlementDate": "2026-09-11",
    "status": "Upcoming",
    "overview": "Disinvestment by Government of India representing a 3% equity stake at an attractive floor price with 5% retail discount."
  },
  {
    "id": "ofs-4",
    "companyName": "SJVN Limited",
    "symbol": "SJVN",
    "slug": "sjvn-ofs-2026",
    "exchange": "NSE & BSE",
    "sellerName": "Government of India & State Govt of HP",
    "sector": "Renewable & Hydro Energy",
    "floorPrice": 128.0,
    "currentMarketPrice": 139.5,
    "discountPercent": 8.24,
    "retailDiscountPercent": 5.0,
    "issueSizeCr": 1350.0,
    "sharesOffered": 96700000,
    "promoterPreHoldingPercent": 81.85,
    "promoterPostHoldingPercent": 75.00,
    "retailQuotaPercent": 10,
    "nonRetailDate": "2026-09-15",
    "retailDate": "2026-09-16",
    "settlementDate": "2026-09-18",
    "status": "Upcoming",
    "overview": "Strategic dilution to align with SEBI's 25% minimum public shareholding guideline."
  },
  {
    "id": "ofs-5",
    "companyName": "Hindustan Aeronautics Limited (HAL)",
    "symbol": "HAL",
    slug: "hal-ofs-completed",
    "exchange": "NSE & BSE",
    "sellerName": "Government of India (Ministry of Defence)",
    "sector": "Defence & Aerospace",
    "floorPrice": 2450.0,
    "currentMarketPrice": 4720.0,
    "discountPercent": 6.50,
    "retailDiscountPercent": 5.0,
    "issueSizeCr": 2800.0,
    "sharesOffered": 11428000,
    "promoterPreHoldingPercent": 75.15,
    "promoterPostHoldingPercent": 71.65,
    "retailQuotaPercent": 10,
    "nonRetailDate": "2026-07-10",
    "retailDate": "2026-07-11",
    "nonRetailSubscriptionTimes": 4.82,
    "settlementDate": "2026-07-15",
    "indicativeClearingPrice": 2480.0,
    "status": "Closed",
    "overview": "Defence PSU stake sale achieved 4.8x oversubscription in non-retail and 3.2x in retail quota."
  },
  {
    "id": "ofs-6",
    "companyName": "Patanjali Foods Limited",
    "symbol": "PATANJALI",
    "slug": "patanjali-foods-ofs",
    "exchange": "NSE & BSE",
    "sellerName": "Patanjali Ayurved Ltd (Promoter Group)",
    "sector": "FMCG & Consumer Foods",
    "floorPrice": 1000.0,
    "currentMarketPrice": 1680.0,
    "discountPercent": 12.50,
    "retailDiscountPercent": 0,
    "issueSizeCr": 2530.0,
    "sharesOffered": 25339000,
    "promoterPreHoldingPercent": 80.82,
    "promoterPostHoldingPercent": 73.82,
    "retailQuotaPercent": 10,
    "nonRetailDate": "2026-06-20",
    "retailDate": "2026-06-21",
    "nonRetailSubscriptionTimes": 2.15,
    "settlementDate": "2026-06-25",
    "indicativeClearingPrice": 1015.0,
    "status": "Closed",
    "overview": "OFS initiated to comply with SEBI 25% public shareholding rule post-merger."
  }
]
